package com.p2sdev.validator;

public enum ValidationStatus {
    EMPTYORNULL, INVALIDUSERNAME, VALIDUSERNAME, INVALIDPASSWORD, PASSWORDNOTMATCHING, VALIDPASSWORD, INVALIDDATE, VALIDDATE, INVALIDDOB, VALIDDOB, DOBTOOYOUNG, INVALIDNAME, VALIDNAME, INVALIDPHONENUMBER, VALIDPHONENUMBER, INVALID, VALID
}

